//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TicketService.Ui.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback XmlIsletOperationCompleted;
        
        private System.Threading.SendOrPostCallback StrIsletOperationCompleted;
        
        private System.Threading.SendOrPostCallback OtobusKalkisOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDOKalkisOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDOVarisOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrenNoktaOperationCompleted;
        
        private System.Threading.SendOrPostCallback HavaAlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResmiTatilGunleriOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnYakinHavaNoktaGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback strEnYakinHavaNoktaGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnYakinKaraNoktaGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback strEnYakinKaraNoktaGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback CiftBiletKontrolEtOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::TicketService.Ui.Properties.Settings.Default.TicketService_Ui_WebReference_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event XmlIsletCompletedEventHandler XmlIsletCompleted;
        
        /// <remarks/>
        public event StrIsletCompletedEventHandler StrIsletCompleted;
        
        /// <remarks/>
        public event OtobusKalkisCompletedEventHandler OtobusKalkisCompleted;
        
        /// <remarks/>
        public event IDOKalkisCompletedEventHandler IDOKalkisCompleted;
        
        /// <remarks/>
        public event IDOVarisCompletedEventHandler IDOVarisCompleted;
        
        /// <remarks/>
        public event TrenNoktaCompletedEventHandler TrenNoktaCompleted;
        
        /// <remarks/>
        public event HavaAlanCompletedEventHandler HavaAlanCompleted;
        
        /// <remarks/>
        public event ResmiTatilGunleriCompletedEventHandler ResmiTatilGunleriCompleted;
        
        /// <remarks/>
        public event EnYakinHavaNoktaGetirCompletedEventHandler EnYakinHavaNoktaGetirCompleted;
        
        /// <remarks/>
        public event strEnYakinHavaNoktaGetirCompletedEventHandler strEnYakinHavaNoktaGetirCompleted;
        
        /// <remarks/>
        public event EnYakinKaraNoktaGetirCompletedEventHandler EnYakinKaraNoktaGetirCompleted;
        
        /// <remarks/>
        public event strEnYakinKaraNoktaGetirCompletedEventHandler strEnYakinKaraNoktaGetirCompleted;
        
        /// <remarks/>
        public event CiftBiletKontrolEtCompletedEventHandler CiftBiletKontrolEtCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlIslet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode XmlIslet(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki) {
            object[] results = this.Invoke("XmlIslet", new object[] {
                        xmlIslem,
                        xmlYetki});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void XmlIsletAsync(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki) {
            this.XmlIsletAsync(xmlIslem, xmlYetki, null);
        }
        
        /// <remarks/>
        public void XmlIsletAsync(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki, object userState) {
            if ((this.XmlIsletOperationCompleted == null)) {
                this.XmlIsletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlIsletOperationCompleted);
            }
            this.InvokeAsync("XmlIslet", new object[] {
                        xmlIslem,
                        xmlYetki}, this.XmlIsletOperationCompleted, userState);
        }
        
        private void OnXmlIsletOperationCompleted(object arg) {
            if ((this.XmlIsletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlIsletCompleted(this, new XmlIsletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StrIslet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StrIslet(string strislem, string stryetki) {
            object[] results = this.Invoke("StrIslet", new object[] {
                        strislem,
                        stryetki});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StrIsletAsync(string strislem, string stryetki) {
            this.StrIsletAsync(strislem, stryetki, null);
        }
        
        /// <remarks/>
        public void StrIsletAsync(string strislem, string stryetki, object userState) {
            if ((this.StrIsletOperationCompleted == null)) {
                this.StrIsletOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStrIsletOperationCompleted);
            }
            this.InvokeAsync("StrIslet", new object[] {
                        strislem,
                        stryetki}, this.StrIsletOperationCompleted, userState);
        }
        
        private void OnStrIsletOperationCompleted(object arg) {
            if ((this.StrIsletCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StrIsletCompleted(this, new StrIsletCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OtobusKalkis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode OtobusKalkis(string ilcelerGetirilsinMi) {
            object[] results = this.Invoke("OtobusKalkis", new object[] {
                        ilcelerGetirilsinMi});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void OtobusKalkisAsync(string ilcelerGetirilsinMi) {
            this.OtobusKalkisAsync(ilcelerGetirilsinMi, null);
        }
        
        /// <remarks/>
        public void OtobusKalkisAsync(string ilcelerGetirilsinMi, object userState) {
            if ((this.OtobusKalkisOperationCompleted == null)) {
                this.OtobusKalkisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOtobusKalkisOperationCompleted);
            }
            this.InvokeAsync("OtobusKalkis", new object[] {
                        ilcelerGetirilsinMi}, this.OtobusKalkisOperationCompleted, userState);
        }
        
        private void OnOtobusKalkisOperationCompleted(object arg) {
            if ((this.OtobusKalkisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OtobusKalkisCompleted(this, new OtobusKalkisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDOKalkis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode IDOKalkis() {
            object[] results = this.Invoke("IDOKalkis", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void IDOKalkisAsync() {
            this.IDOKalkisAsync(null);
        }
        
        /// <remarks/>
        public void IDOKalkisAsync(object userState) {
            if ((this.IDOKalkisOperationCompleted == null)) {
                this.IDOKalkisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDOKalkisOperationCompleted);
            }
            this.InvokeAsync("IDOKalkis", new object[0], this.IDOKalkisOperationCompleted, userState);
        }
        
        private void OnIDOKalkisOperationCompleted(object arg) {
            if ((this.IDOKalkisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDOKalkisCompleted(this, new IDOKalkisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDOVaris", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode IDOVaris(string key) {
            object[] results = this.Invoke("IDOVaris", new object[] {
                        key});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void IDOVarisAsync(string key) {
            this.IDOVarisAsync(key, null);
        }
        
        /// <remarks/>
        public void IDOVarisAsync(string key, object userState) {
            if ((this.IDOVarisOperationCompleted == null)) {
                this.IDOVarisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDOVarisOperationCompleted);
            }
            this.InvokeAsync("IDOVaris", new object[] {
                        key}, this.IDOVarisOperationCompleted, userState);
        }
        
        private void OnIDOVarisOperationCompleted(object arg) {
            if ((this.IDOVarisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDOVarisCompleted(this, new IDOVarisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrenNokta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode TrenNokta() {
            object[] results = this.Invoke("TrenNokta", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TrenNoktaAsync() {
            this.TrenNoktaAsync(null);
        }
        
        /// <remarks/>
        public void TrenNoktaAsync(object userState) {
            if ((this.TrenNoktaOperationCompleted == null)) {
                this.TrenNoktaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrenNoktaOperationCompleted);
            }
            this.InvokeAsync("TrenNokta", new object[0], this.TrenNoktaOperationCompleted, userState);
        }
        
        private void OnTrenNoktaOperationCompleted(object arg) {
            if ((this.TrenNoktaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrenNoktaCompleted(this, new TrenNoktaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HavaAlan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode HavaAlan() {
            object[] results = this.Invoke("HavaAlan", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void HavaAlanAsync() {
            this.HavaAlanAsync(null);
        }
        
        /// <remarks/>
        public void HavaAlanAsync(object userState) {
            if ((this.HavaAlanOperationCompleted == null)) {
                this.HavaAlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHavaAlanOperationCompleted);
            }
            this.InvokeAsync("HavaAlan", new object[0], this.HavaAlanOperationCompleted, userState);
        }
        
        private void OnHavaAlanOperationCompleted(object arg) {
            if ((this.HavaAlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HavaAlanCompleted(this, new HavaAlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResmiTatilGunleri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ResmiTatilGunleri(string yil) {
            object[] results = this.Invoke("ResmiTatilGunleri", new object[] {
                        yil});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ResmiTatilGunleriAsync(string yil) {
            this.ResmiTatilGunleriAsync(yil, null);
        }
        
        /// <remarks/>
        public void ResmiTatilGunleriAsync(string yil, object userState) {
            if ((this.ResmiTatilGunleriOperationCompleted == null)) {
                this.ResmiTatilGunleriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResmiTatilGunleriOperationCompleted);
            }
            this.InvokeAsync("ResmiTatilGunleri", new object[] {
                        yil}, this.ResmiTatilGunleriOperationCompleted, userState);
        }
        
        private void OnResmiTatilGunleriOperationCompleted(object arg) {
            if ((this.ResmiTatilGunleriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResmiTatilGunleriCompleted(this, new ResmiTatilGunleriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnYakinHavaNoktaGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode EnYakinHavaNoktaGetir(string karaNokta) {
            object[] results = this.Invoke("EnYakinHavaNoktaGetir", new object[] {
                        karaNokta});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void EnYakinHavaNoktaGetirAsync(string karaNokta) {
            this.EnYakinHavaNoktaGetirAsync(karaNokta, null);
        }
        
        /// <remarks/>
        public void EnYakinHavaNoktaGetirAsync(string karaNokta, object userState) {
            if ((this.EnYakinHavaNoktaGetirOperationCompleted == null)) {
                this.EnYakinHavaNoktaGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnYakinHavaNoktaGetirOperationCompleted);
            }
            this.InvokeAsync("EnYakinHavaNoktaGetir", new object[] {
                        karaNokta}, this.EnYakinHavaNoktaGetirOperationCompleted, userState);
        }
        
        private void OnEnYakinHavaNoktaGetirOperationCompleted(object arg) {
            if ((this.EnYakinHavaNoktaGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnYakinHavaNoktaGetirCompleted(this, new EnYakinHavaNoktaGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/strEnYakinHavaNoktaGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string strEnYakinHavaNoktaGetir(string karaNokta) {
            object[] results = this.Invoke("strEnYakinHavaNoktaGetir", new object[] {
                        karaNokta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void strEnYakinHavaNoktaGetirAsync(string karaNokta) {
            this.strEnYakinHavaNoktaGetirAsync(karaNokta, null);
        }
        
        /// <remarks/>
        public void strEnYakinHavaNoktaGetirAsync(string karaNokta, object userState) {
            if ((this.strEnYakinHavaNoktaGetirOperationCompleted == null)) {
                this.strEnYakinHavaNoktaGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstrEnYakinHavaNoktaGetirOperationCompleted);
            }
            this.InvokeAsync("strEnYakinHavaNoktaGetir", new object[] {
                        karaNokta}, this.strEnYakinHavaNoktaGetirOperationCompleted, userState);
        }
        
        private void OnstrEnYakinHavaNoktaGetirOperationCompleted(object arg) {
            if ((this.strEnYakinHavaNoktaGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.strEnYakinHavaNoktaGetirCompleted(this, new strEnYakinHavaNoktaGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnYakinKaraNoktaGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnYakinKaraNoktaGetir(string havaKod) {
            object[] results = this.Invoke("EnYakinKaraNoktaGetir", new object[] {
                        havaKod});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnYakinKaraNoktaGetirAsync(string havaKod) {
            this.EnYakinKaraNoktaGetirAsync(havaKod, null);
        }
        
        /// <remarks/>
        public void EnYakinKaraNoktaGetirAsync(string havaKod, object userState) {
            if ((this.EnYakinKaraNoktaGetirOperationCompleted == null)) {
                this.EnYakinKaraNoktaGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnYakinKaraNoktaGetirOperationCompleted);
            }
            this.InvokeAsync("EnYakinKaraNoktaGetir", new object[] {
                        havaKod}, this.EnYakinKaraNoktaGetirOperationCompleted, userState);
        }
        
        private void OnEnYakinKaraNoktaGetirOperationCompleted(object arg) {
            if ((this.EnYakinKaraNoktaGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnYakinKaraNoktaGetirCompleted(this, new EnYakinKaraNoktaGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/strEnYakinKaraNoktaGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string strEnYakinKaraNoktaGetir(string havaKod) {
            object[] results = this.Invoke("strEnYakinKaraNoktaGetir", new object[] {
                        havaKod});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void strEnYakinKaraNoktaGetirAsync(string havaKod) {
            this.strEnYakinKaraNoktaGetirAsync(havaKod, null);
        }
        
        /// <remarks/>
        public void strEnYakinKaraNoktaGetirAsync(string havaKod, object userState) {
            if ((this.strEnYakinKaraNoktaGetirOperationCompleted == null)) {
                this.strEnYakinKaraNoktaGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstrEnYakinKaraNoktaGetirOperationCompleted);
            }
            this.InvokeAsync("strEnYakinKaraNoktaGetir", new object[] {
                        havaKod}, this.strEnYakinKaraNoktaGetirOperationCompleted, userState);
        }
        
        private void OnstrEnYakinKaraNoktaGetirOperationCompleted(object arg) {
            if ((this.strEnYakinKaraNoktaGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.strEnYakinKaraNoktaGetirCompleted(this, new strEnYakinKaraNoktaGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CiftBiletKontrolEt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CiftBiletKontrolEt(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad) {
            object[] results = this.Invoke("CiftBiletKontrolEt", new object[] {
                        islem,
                        firmaNo,
                        tarih,
                        kalkis,
                        varis,
                        yolcuAd,
                        yolcuSoyad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CiftBiletKontrolEtAsync(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad) {
            this.CiftBiletKontrolEtAsync(islem, firmaNo, tarih, kalkis, varis, yolcuAd, yolcuSoyad, null);
        }
        
        /// <remarks/>
        public void CiftBiletKontrolEtAsync(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad, object userState) {
            if ((this.CiftBiletKontrolEtOperationCompleted == null)) {
                this.CiftBiletKontrolEtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCiftBiletKontrolEtOperationCompleted);
            }
            this.InvokeAsync("CiftBiletKontrolEt", new object[] {
                        islem,
                        firmaNo,
                        tarih,
                        kalkis,
                        varis,
                        yolcuAd,
                        yolcuSoyad}, this.CiftBiletKontrolEtOperationCompleted, userState);
        }
        
        private void OnCiftBiletKontrolEtOperationCompleted(object arg) {
            if ((this.CiftBiletKontrolEtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CiftBiletKontrolEtCompleted(this, new CiftBiletKontrolEtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void XmlIsletCompletedEventHandler(object sender, XmlIsletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlIsletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlIsletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void StrIsletCompletedEventHandler(object sender, StrIsletCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StrIsletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StrIsletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OtobusKalkisCompletedEventHandler(object sender, OtobusKalkisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OtobusKalkisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OtobusKalkisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IDOKalkisCompletedEventHandler(object sender, IDOKalkisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDOKalkisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDOKalkisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IDOVarisCompletedEventHandler(object sender, IDOVarisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDOVarisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDOVarisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TrenNoktaCompletedEventHandler(object sender, TrenNoktaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrenNoktaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrenNoktaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HavaAlanCompletedEventHandler(object sender, HavaAlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HavaAlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HavaAlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ResmiTatilGunleriCompletedEventHandler(object sender, ResmiTatilGunleriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResmiTatilGunleriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResmiTatilGunleriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EnYakinHavaNoktaGetirCompletedEventHandler(object sender, EnYakinHavaNoktaGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnYakinHavaNoktaGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnYakinHavaNoktaGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void strEnYakinHavaNoktaGetirCompletedEventHandler(object sender, strEnYakinHavaNoktaGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class strEnYakinHavaNoktaGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal strEnYakinHavaNoktaGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EnYakinKaraNoktaGetirCompletedEventHandler(object sender, EnYakinKaraNoktaGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnYakinKaraNoktaGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnYakinKaraNoktaGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void strEnYakinKaraNoktaGetirCompletedEventHandler(object sender, strEnYakinKaraNoktaGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class strEnYakinKaraNoktaGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal strEnYakinKaraNoktaGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CiftBiletKontrolEtCompletedEventHandler(object sender, CiftBiletKontrolEtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiftBiletKontrolEtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CiftBiletKontrolEtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591